#!/bin/bash

set -Ceux

ARGS=${@:2}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CURRENT_DIR_NAME=${PWD##*/}

case $1 in
"up")
  docker compose up -d
;;
"down")
  docker compose down
;;
"restart")
  docker compose down
  docker compose up
;;
"build")
  docker compose build
;;
"exec")
  docker compose exec goapp $ARGS
;;
*)
  echo Unexpected command: $1
  exit 1
;;
esac
